version: "3.9"

services:
    devnet:
        platform: "linux/amd64"
        image: ghcr.io/foundry-rs/foundry:latest
        entrypoint: /usr/local/bin/anvil
        command: -f https://1rpc.io/sepolia --chain-id 31337 -b 1
        ports:
            - "8545:8545"
        environment:
            ANVIL_IP_ADDR: 0.0.0.0
        pull_policy: always
